version: '2'

services:
    consul:
        image: daocloud.io/jsongo/consul
        container_name: consul
        network_mode: host
        restart: always
        environment:
          - NODE_NAME=gamesvr
        command: agent -server -bind 127.0.0.1 -bootstrap -advertise 123.56.85.164 -log-level debug -client 127.0.0.1 -ui
        volumes:
            - /data/consul:/consul/data

    consul-registrator:
        tty: true
        image: gliderlabs/registrator
        container_name: consul-registrator
        network_mode: host
        restart: always
        command:
            - consul://127.0.0.1:8500
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        stdin_open: true
