version: '2'

services:
    consul-watch-services:
        image: daocloud.io/jsongo/consul-watch:latest
        container_name: consul-watch-services
        network_mode: host
        restart: always
        environment:
            VERSION: 1.0.0
            WATCH_TYPE: checks
            WATCH_STATE: critical 
            SCRIPT: /script.sh
        command: sh -c /entrypoint.sh
        volumes:
            - ./script.sh:/script.sh
            - ./main.py:/main.py
            - .:/data
