version: '2'

services:
    consul-watch-conf:
        image: daocloud.io/jsongo/consul-watch
        container_name: consul-watch-conf
        network_mode: host
        environment:
            VERSION: 1.0.1
            WATCH_TYPE: keyprefix
            WATCH_TARGET: jinyu/conf/
        volumes:
            - /data/code/script/conf-update.sh:/script.sh
