version: '2'

services:
    consul-watch-conf:
        image: daocloud.io/jsongo/consul-watch:latest
        container_name: consul-watch-conf
        network_mode: host
        environment:
            VERSION: 1.0.1
            WATCH_TYPE: keyprefix
            WATCH_TARGET: jinyu/conf/
            SCRIPT: /conf-update.sh
        command: sh -c /entrypoint.sh
        volumes:
            - ./conf-update.sh:/conf-update.sh
